-- Only Changes to NDefines.NCountry should be here.

	--Culture
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 3

	--Dictatorship
NDefines.NCountry.DICTATORSHIP_TRADITION_FOR_MONARCHY = 20
NDefines.NCountry.DICTATORSHIP_TRADITION_FOR_REPUBLIC = 60

	--Estate
NDefines.NCountry.ESTATE_MIN_DISTRIBUTED_CROWNLAND = 33.0
NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 20
NDefines.NCountry.ESTATE_AGENDA_ABOUT_TO_EXPIRE_WARNING = 425
NDefines.NCountry.ESTATE_LOYALTY_DECAY_BASE_MIN = 6.0
NDefines.NCountry.ESTATE_LOYALTY_DECAY_BASE_MAX = 9.0

	--Idea
NDefines.NCountry.FREE_IDEA_GROUP_COST = 5
NDefines.NCountry.IDEA_TO_TECH = -0.01
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.35
NDefines.NCountry.PS_BUY_IDEA = 300

	--Merchant Republuic
NDefines.NCountry.MERCHANT_REPUBLIC_SIZE_LIMIT = 9999

	--Policies
NDefines.NCountry.BASE_POSSIBLE_POLICIES = 4
NDefines.NCountry.MAX_ACTIVE_POLICIES = 12
NDefines.NCountry.MINIMUM_POLICY_TIME = 3

	--Professionalism
NDefines.NCountry.HIGH_ARMY_PROFESSIONALISM_MIN_RANGE = 0
NDefines.NCountry.HIGH_ARMY_PROFESSIONALISM_MAX_RANGE = 1
NDefines.NCountry.LOW_ARMY_PROFESSIONALISM_MIN_RANGE = 0
NDefines.NCountry.LOW_ARMY_PROFESSIONALISM_MAX_RANGE = 1
NDefines.NCountry.MAX_ARMY_PROFESSIONALISM = 1

	--Scripted Advisor
NDefines.NCountry.SCRIPTED_ADVISOR_DISCOUNT = 0.33

	--State Maintenance
NDefines.NCountry.STATE_MAINTENANCE_CONTINENT_FACTOR = -0.5
NDefines.NCountry.STATE_MAINTENANCE_CULTURE_FACTOR = 0.15
NDefines.NCountry.STATE_MAINTENANCE_DEV_FACTOR = 0.012
NDefines.NCountry.STATE_MAINTENANCE_DISTANCE_FACTOR = 0.002

	--State Privilege
NDefines.NCountry.STATE_PRIVILEGE_ADMIN_COST = 1	

	--Tariffs
NDefines.NCountry.PS_LOWER_TARIFFS = 5
NDefines.NCountry.PS_RAISE_TARIFFS = 10
