-- Only Changes to NDefines.NReligion should be here.

	--Papal
NDefines.NReligion.APPOINT_CARDINAL_INFLUENCE = 5
NDefines.NReligion.APPOINT_CARDINAL_CORRUPTION = 1
NDefines.NReligion.YEARLY_POPE_INVESTED_INFLUENCE_PER_CARDINAL = 0.01
NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_COST = 1.5
NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_TREASURY_CONTRIBUTION = 0.1
